name : "Deploying to EC2 instance"
on:
  push:
    branches:
      - main
#the problem while manual ssh into instance would be known host accpetance which is not 
#automatically on terminal when github ubuntu will to do.

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install the modules
        run: npm install

      - name : Run the server
        run : npm run start